DROP TABLE IF EXISTS users;
create table users(
  id int auto_increment primary key,
  fullname varchar(50) not null,
  email varchar(50) not null unique,
  pw varchar(50) not null
);
DROP TABLE IF EXISTS messages;
create table messages(
  id int auto_increment primary key,
  sender_id int not null,
  receiver_id int not null,
  email_subject varchar(100),
  email_body text,
  attachment text,
  created_at datetime not null,
  foreign key (sender_id) references users(id) ON DELETE CASCADE ON UPDATE CASCADE,
  foreign key (receiver_id) references users(id) ON DELETE CASCADE ON UPDATE CASCADE
);

INSERT INTO users VALUES
  (1, 'Pham Van A','a@a.com', 'aaa12345'),
  (2, 'Nguyen Van B','b@b.com', 'bbb12345'),
  (3, 'Tran Thi C','c@c.com', 'ccc12345');

INSERT INTO messages (sender_id, receiver_id, email_subject, email_body,created_at) VALUES
  (1, 2, 'Invitation to Project Kickoff Meeting', 'I hope this email finds you well. I am excited to announce that we will be starting a new project next week, and I would like to invite you all to the project kickoff meeting. Please come prepared with any questions, ideas, or suggestions you may have regarding the project. Your input and expertise are valuable and will contribute to the project.', '2023-11-12'),
  (1, 3, 'Request for Meeting Reschedule', 'I hope this email finds you well. I wanted to reach out and request a reschedule for our upcoming meeting scheduled for Dec 1 at 8pm. Unfortunately, due to unforeseen circumstances, I have a conflicting appointment that I cannot change. I apologize for any inconvenience this may cause, and I understand the importance of the meeting. Is it possible to reschedule the meeting to a later date or time that works for you? Please let me know your availability, and we can find a suitable alternative. Thank you for your understanding, and I look forward to your response.', '2023-1-10'),
  (2, 1, 'Response to Project Kickoff Meeting', 'I hope this email finds you well. I am excited to announce that we will be starting a new project next week, and I would like to invite you all to the project kickoff meeting. Please come prepared with any questions, ideas, or suggestions you may have regarding the project. Your input and expertise are valuable and will contribute to the project.', '2023-10-28'),
  (3, 1, 'Team Meeting Next Week', 'During the meeting, we will discuss the progress of ongoing projects, address any challenges or roadblocks, and share important updates. It is essential that all team members attend to ensure alignment and effective collaboration. Please come prepared with status updates, any pending action items, and any topics you would like to discuss as part of the agenda. If you are unable to attend, kindly let me know in advance, and we will make necessary arrangements. Looking forward to seeing you all tomorrow and having a productive meeting.', '2023-7-12'),
  (2, 1, 'Confirmation of Conference Registration', 'I hope this email finds you well. I am writing to confirm that your registration for the upcoming conference on Conference Name has been successfully processed. The conference will take place on Dec 1 at Hanoi. Please make sure to arrive on time and bring any necessary materials, such as your ID badge or registration confirmation. We have an exciting lineup of keynote speakers, breakout sessions, and networking opportunities planned for the conference. It promises to be an enriching experience for all attendees. If you have any questions or need further information, please do not hesitate to reach out to our conference support team. Thank you for your participation, and we look forward to welcoming you at the conference.', '2023-9-10'),
  (1, 3, 'Invitation to Project Kickoff Meeting', 'I hope this email finds you well. I am excited to announce that we will be starting a new project next week, and I would like to invite you all to the project kickoff meeting. Please come prepared with any questions, ideas, or suggestions you may have regarding the project. Your input and expertise are valuable and will contribute to the project.', '2023-11-12'),
  (3, 1, 'Information about Meeting Reschedule', 'I hope this email finds you well. I wanted to reach out and request a reschedule for our upcoming meeting scheduled for Dec 1 at 8pm. Unfortunately, due to unforeseen circumstances, I have a conflicting appointment that I cannot change. I apologize for any inconvenience this may cause, and I understand the importance of the meeting. Is it possible to reschedule the meeting to a later date or time that works for you? Please let me know your availability, and we can find a suitable alternative. Thank you for your understanding, and I look forward to your response.', '2023-11-18'),
  (2, 3, 'Response to Project Meeting', 'I hope this email finds you well. I am excited to announce that we will be starting a new project next week, and I would like to invite you all to the project kickoff meeting. Please come prepared with any questions, ideas, or suggestions you may have regarding the project. Your input and expertise are valuable and will contribute to the project.', '2023-10-28'),
  (2, 1, 'Announcement about team meeting tomorrow', 'During the meeting, we will discuss the progress of ongoing projects, address any challenges or roadblocks, and share important updates. It is essential that all team members attend to ensure alignment and effective collaboration. Please come prepared with status updates, any pending action items, and any topics you would like to discuss as part of the agenda. If you are unable to attend, kindly let me know in advance, and we will make necessary arrangements. Looking forward to seeing you all tomorrow and having a productive meeting.', '2023-8-14'),
  (1, 2, 'Confirmation of Conference Registration', 'I hope this email finds you well. I am writing to confirm that your registration for the upcoming conference on Conference Name has been successfully processed. The conference will take place on Dec 1 at Hanoi. Please make sure to arrive on time and bring any necessary materials, such as your ID badge or registration confirmation. We have an exciting lineup of keynote speakers, breakout sessions, and networking opportunities planned for the conference. It promises to be an enriching experience for all attendees. If you have any questions or need further information, please do not hesitate to reach out to our conference support team. Thank you for your participation, and we look forward to welcoming you at the conference.', '2023-8-15'),
  (1, 2, 'Invitation to Project Kickoff Meeting', 'I hope this email finds you well. I am excited to announce that we will be starting a new project next week, and I would like to invite you all to the project kickoff meeting. Please come prepared with any questions, ideas, or suggestions you may have regarding the project. Your input and expertise are valuable and will contribute to the project.', '2023-11-12'),
  (1, 3, 'Request for Meeting Reschedule', 'I hope this email finds you well. I wanted to reach out and request a reschedule for our upcoming meeting scheduled for Dec 1 at 8pm. Unfortunately, due to unforeseen circumstances, I have a conflicting appointment that I cannot change. I apologize for any inconvenience this may cause, and I understand the importance of the meeting. Is it possible to reschedule the meeting to a later date or time that works for you? Please let me know your availability, and we can find a suitable alternative. Thank you for your understanding, and I look forward to your response.', '2023-10-10'),
  (2, 1, 'Response to Project Kickoff Meeting', 'I hope this email finds you well. I am excited to announce that we will be starting a new project next week, and I would like to invite you all to the project kickoff meeting. Please come prepared with any questions, ideas, or suggestions you may have regarding the project. Your input and expertise are valuable and will contribute to the project.', '2023-10-28'),
  (3, 1, 'Team Meeting Tomorrow', 'During the meeting, we will discuss the progress of ongoing projects, address any challenges or roadblocks, and share important updates. It is essential that all team members attend to ensure alignment and effective collaboration. Please come prepared with status updates, any pending action items, and any topics you would like to discuss as part of the agenda. If you are unable to attend, kindly let me know in advance, and we will make necessary arrangements. Looking forward to seeing you all tomorrow and having a productive meeting.', '2023-6-12'),
  (3, 2, 'Confirmation of Conference Registration', 'I hope this email finds you well. I am writing to confirm that your registration for the upcoming conference on Conference Name has been successfully processed. The conference will take place on Dec 1 at Hanoi. Please make sure to arrive on time and bring any necessary materials, such as your ID badge or registration confirmation. We have an exciting lineup of keynote speakers, breakout sessions, and networking opportunities planned for the conference. It promises to be an enriching experience for all attendees. If you have any questions or need further information, please do not hesitate to reach out to our conference support team. Thank you for your participation, and we look forward to welcoming you at the conference.', '2023-5-25'),
  (1, 3, 'Announcement about Project Kickoff Meeting', 'I hope this email finds you well. I am excited to announce that we will be starting a new project next week, and I would like to invite you all to the project kickoff meeting. Please come prepared with any questions, ideas, or suggestions you may have regarding the project. Your input and expertise are valuable and will contribute to the project.', '2023-11-12'),
  (3, 1, 'Request for Meeting Reschedule', 'I hope this email finds you well. I wanted to reach out and request a reschedule for our upcoming meeting scheduled for Dec 1 at 8pm. Unfortunately, due to unforeseen circumstances, I have a conflicting appointment that I cannot change. I apologize for any inconvenience this may cause, and I understand the importance of the meeting. Is it possible to reschedule the meeting to a later date or time that works for you? Please let me know your availability, and we can find a suitable alternative. Thank you for your understanding, and I look forward to your response.', '2023-11-24'),
  (2, 3, 'Reply to Project Kickoff Meeting', 'I hope this email finds you well. I am excited to announce that we will be starting a new project next week, and I would like to invite you all to the project kickoff meeting. Please come prepared with any questions, ideas, or suggestions you may have regarding the project. Your input and expertise are valuable and will contribute to the project.', '2023-10-28'),
  (2, 1, 'Team Meeting Tomorrow', 'During the meeting, we will discuss the progress of ongoing projects, address any challenges or roadblocks, and share important updates. It is essential that all team members attend to ensure alignment and effective collaboration. Please come prepared with status updates, any pending action items, and any topics you would like to discuss as part of the agenda. If you are unable to attend, kindly let me know in advance, and we will make necessary arrangements. Looking forward to seeing you all tomorrow and having a productive meeting.', '2023-9-1'),
  (2, 3, 'Confirmation of Conference Registration', 'I hope this email finds you well. I am writing to confirm that your registration for the upcoming conference on Conference Name has been successfully processed. The conference will take place on Dec 1 at Hanoi. Please make sure to arrive on time and bring any necessary materials, such as your ID badge or registration confirmation. We have an exciting lineup of keynote speakers, breakout sessions, and networking opportunities planned for the conference. It promises to be an enriching experience for all attendees. If you have any questions or need further information, please do not hesitate to reach out to our conference support team. Thank you for your participation, and we look forward to welcoming you at the conference.', '2023-9-15');

